### ISSUE TITLE
Branch integration does not work when Jira item is with lower case

### ISSUE THREAD

**Issue by dimofeev** [integrations/jira#179]
HI guys,

 We found out that when you name you branch using the following way: 

 `test-1234-my-branch` the integration is not working as expected and the branch does not appear in the JIRA item. Naming the branch using upper case works fine (i.e. `test-1234-my-branch`).

 Is there any specific reason for that limitation?

Best,
 Dimo

**Comment by tcbyrd** [comment]
Hi @dimofeev! Basically this is enforced by the Jira Issue Key format

https://confluence.atlassian.com/jirasoftwarecloud/referencing-issues-in-your-development-work-777002789.html
> In all cases, the issue key must use to the default Jira key format – that is, **two or more uppercase letters** ([A-Z][A-Z]+), followed by a hyphen and the issue number. For example, ABC-123.

In practice, this also helps keep false positives to a minimum since it's less common for branch names to starts with two uppercase letters. Hope that helps!
