### ISSUE TITLE
Sync progress

### ISSUE THREAD

**Issue by jnraine** [integrations/jira#216]
The initial sync can take minutes or hours. Until it is complete, users migrating from DVCS won’t see data from the new integration. While #215 should reduce the sync times, we can improve the experience by telling the user how long they'll have to wait.

We can sync about 50 commits per second and can determine the number of commits left to sync using the API page count. With this in mind, we should be able to provide percent complete and estimate time remaining.

**Comment by reillydavis** [comment]
Can it take days? Is there a timeout? How long should we wait before trying to uninstall/reinstall?

**Comment by jimgraham** [comment]
We're on multi-day. Is there any logging / additional info to know where we are in the process?

**Comment by JustAndrewAFSA** [comment]
I don't think anyone has commented on this for a while.  It it possible to at least build a simple REST service or change the UI to indicate the sync is still running (and what it's currently processing). Something like that gives us a simple indication if it's stalled or what file it's currently processing. In a similar situation to the others where I think it's going to take days for this to run (since we have a lot of projects + branches), but all we have is a status that will change from 'ACTIVE' to 'COMPLETED' at an unknown point in the future. Something simple like that would let us know if it's actually stalled (and needs to be restated) or if it's still processing different files.

**Comment by rachellerathbone** [comment]
Closing as we have recently deployed a change to indicate the number of repos installed out of the total number of repos to sync.
