### ISSUE TITLE
Cannot see development panel in Jira after installing

### ISSUE THREAD

**Issue by yinchuandong** [integrations/jira#378]
Hi there, 

I followed the installation steps in readme but I cannot see development panel in jira issue. Can anybody review the whole installation process in Jira? Jira had a big release in UI this year and it might break something. Moreover, I saw many people met the same issue in Jira App Marketplace. Hope you guys can make it easier for people to start. Thanks in advance

**Comment by scryan7371** [comment]
Same issue here.  Very frustrating as we would like to use both Github and Jira but can't get it to work

**Comment by Alecise** [comment]
Hi, for everyone stumbling upon this mistery, I may have find the answer :

In order to see the Development Panel on the issues, you need to have the permission to view it.

By default, users that are allowed to see the development Panel are those with a Project role of : developers, atlassian-addons-project-access
I didn't see it because I was an admin, and not a developer.

I solved this by adding my role to the permission, in Cog Icon > Issues > Permission Schemes > {the permission scheme where the projects are involved} > View Development Tools :)

Hope it helps !

Sources : 
https://support.atlassian.com/jira-software-cloud/docs/view-development-information-for-an-issue/#Viewingthedevelopmentinformationforanissue-Beforeyoubegin
https://confluence.atlassian.com/jirakb/how-to-remove-or-edit-access-to-development-panel-701268686.html

**Comment by rachellerathbone** [comment]
Hi @yinchuandong and @scryan7371. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Please let me know if you are still experiencing this issue and provide any relevant screenshots. Happy to help you both try and resolve this.

**Comment by rachellerathbone** [comment]
As it has been almost 2 months with no response, closing this issue. Please feel free to reopen if needed.
