### ISSUE TITLE
[GitHub API] Update your access token to the new format

### ISSUE THREAD

**Issue by doring7** [integrations/jira#495]
Github asks me to update my token.
How can I do this in JIRA when I have done this ?

https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

**Comment by dimitarcl** [comment]
I want to know the same.

The email says :
> We encourage you to reset any authentication tokens used by this app, as well as tokens used by any other apps you may have, with our [reset token API](https://docs.github.com/en/rest/reference/apps#reset-a-token/).

But I can't see anything in JIRA or GitHub that seems that it would trigger the reset token API.

I guess, I can remove and reinstall the integration, but I prefer to avoid that if possible.

**Comment by mboudreau** [comment]
I find it really weird that Github is sending an email to you, the users about this integration since it should be the owners that would need to update things.

Either way, the good news about this integration is that we _do not store any kind of github auth tokens anywhere_. Hence we have nothing to update.  The only auth token used is when you first install the app where there's an oauth flow to assess the permissions of the user being able to install the app on a particular organization, but that oauth token is stored only for that specific session then thrown away.

Feel free to look through the DB schema or the code, specifically the src/frontend/github-client-middleware.js file, were we create the `GithubAPI` object that's used throughout the app.  The token used here is either the oauth token mentioned earlier which is temporary and per session or we used the token given to use by octokit is which based on the Github app installation and specific app private key which is referenced in the src/configure-robot.js file:
```
const {token} = await api.auth({
    type: 'installation',
    installationId: inst.data[0].id,
  });
```

Unless there's something else that I've missed or you're getting a problem with your installation, I'm going to close this ticket as it's a non-issue.  Cheers :)
